# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import tts_pb2 as tts_dot_tts__pb2


class TTSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.inference = channel.unary_stream(
                '/tts.TTS/inference',
                request_serializer=tts_dot_tts__pb2.Text.SerializeToString,
                response_deserializer=tts_dot_tts__pb2.InferenceResult.FromString,
                )
        self.stream_inference = channel.stream_stream(
                '/tts.TTS/stream_inference',
                request_serializer=tts_dot_tts__pb2.Text.SerializeToString,
                response_deserializer=tts_dot_tts__pb2.InferenceResult.FromString,
                )
        self.stream_inference_fake = channel.stream_stream(
                '/tts.TTS/stream_inference_fake',
                request_serializer=tts_dot_tts__pb2.Text.SerializeToString,
                response_deserializer=tts_dot_tts__pb2.InferenceResult.FromString,
                )
        self.duration_inference = channel.unary_stream(
                '/tts.TTS/duration_inference',
                request_serializer=tts_dot_tts__pb2.Text.SerializeToString,
                response_deserializer=tts_dot_tts__pb2.DurationInferenceResult.FromString,
                )
        self.check_input_text = channel.unary_unary(
                '/tts.TTS/check_input_text',
                request_serializer=tts_dot_tts__pb2.Text.SerializeToString,
                response_deserializer=tts_dot_tts__pb2.CheckInputTextResult.FromString,
                )
        self.extract_speaker_vector = channel.unary_unary(
                '/tts.TTS/extract_speaker_vector',
                request_serializer=tts_dot_tts__pb2.SpeakerInfo.SerializeToString,
                response_deserializer=tts_dot_tts__pb2.SpeakerVector.FromString,
                )
        self.get_version = channel.unary_unary(
                '/tts.TTS/get_version',
                request_serializer=tts_dot_tts__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=tts_dot_tts__pb2.Version.FromString,
                )
        self.split_text = channel.unary_unary(
                '/tts.TTS/split_text',
                request_serializer=tts_dot_tts__pb2.Text.SerializeToString,
                response_deserializer=tts_dot_tts__pb2.SplitTextResult.FromString,
                )


class TTSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def inference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stream_inference(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stream_inference_fake(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def duration_inference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def check_input_text(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def extract_speaker_vector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def split_text(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'inference': grpc.unary_stream_rpc_method_handler(
                    servicer.inference,
                    request_deserializer=tts_dot_tts__pb2.Text.FromString,
                    response_serializer=tts_dot_tts__pb2.InferenceResult.SerializeToString,
            ),
            'stream_inference': grpc.stream_stream_rpc_method_handler(
                    servicer.stream_inference,
                    request_deserializer=tts_dot_tts__pb2.Text.FromString,
                    response_serializer=tts_dot_tts__pb2.InferenceResult.SerializeToString,
            ),
            'stream_inference_fake': grpc.stream_stream_rpc_method_handler(
                    servicer.stream_inference_fake,
                    request_deserializer=tts_dot_tts__pb2.Text.FromString,
                    response_serializer=tts_dot_tts__pb2.InferenceResult.SerializeToString,
            ),
            'duration_inference': grpc.unary_stream_rpc_method_handler(
                    servicer.duration_inference,
                    request_deserializer=tts_dot_tts__pb2.Text.FromString,
                    response_serializer=tts_dot_tts__pb2.DurationInferenceResult.SerializeToString,
            ),
            'check_input_text': grpc.unary_unary_rpc_method_handler(
                    servicer.check_input_text,
                    request_deserializer=tts_dot_tts__pb2.Text.FromString,
                    response_serializer=tts_dot_tts__pb2.CheckInputTextResult.SerializeToString,
            ),
            'extract_speaker_vector': grpc.unary_unary_rpc_method_handler(
                    servicer.extract_speaker_vector,
                    request_deserializer=tts_dot_tts__pb2.SpeakerInfo.FromString,
                    response_serializer=tts_dot_tts__pb2.SpeakerVector.SerializeToString,
            ),
            'get_version': grpc.unary_unary_rpc_method_handler(
                    servicer.get_version,
                    request_deserializer=tts_dot_tts__pb2.GetVersionRequest.FromString,
                    response_serializer=tts_dot_tts__pb2.Version.SerializeToString,
            ),
            'split_text': grpc.unary_unary_rpc_method_handler(
                    servicer.split_text,
                    request_deserializer=tts_dot_tts__pb2.Text.FromString,
                    response_serializer=tts_dot_tts__pb2.SplitTextResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.TTS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TTS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tts.TTS/inference',
            tts_dot_tts__pb2.Text.SerializeToString,
            tts_dot_tts__pb2.InferenceResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stream_inference(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/tts.TTS/stream_inference',
            tts_dot_tts__pb2.Text.SerializeToString,
            tts_dot_tts__pb2.InferenceResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stream_inference_fake(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/tts.TTS/stream_inference_fake',
            tts_dot_tts__pb2.Text.SerializeToString,
            tts_dot_tts__pb2.InferenceResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def duration_inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tts.TTS/duration_inference',
            tts_dot_tts__pb2.Text.SerializeToString,
            tts_dot_tts__pb2.DurationInferenceResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def check_input_text(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tts.TTS/check_input_text',
            tts_dot_tts__pb2.Text.SerializeToString,
            tts_dot_tts__pb2.CheckInputTextResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def extract_speaker_vector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tts.TTS/extract_speaker_vector',
            tts_dot_tts__pb2.SpeakerInfo.SerializeToString,
            tts_dot_tts__pb2.SpeakerVector.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tts.TTS/get_version',
            tts_dot_tts__pb2.GetVersionRequest.SerializeToString,
            tts_dot_tts__pb2.Version.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def split_text(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tts.TTS/split_text',
            tts_dot_tts__pb2.Text.SerializeToString,
            tts_dot_tts__pb2.SplitTextResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
